#!/usr/bin/env python3
"""
build-html.py

Generates:
  - Individual model pages at models/{slug}/index.html
  - Models grid page at models.html
  - Sitemap at sitemap.xml

Usage:
  python build-html.py

Zero dependencies — uses only Python standard library.
"""

import os
import json
import glob
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent if SCRIPT_DIR.name == "scripts" else SCRIPT_DIR

SITE_URL = "https://juke32.com"
MODELS_DATA_DIR = str(REPO_ROOT / "models")
MODELS_OUTPUT_DIR = str(REPO_ROOT / "models")
GRID_OUTPUT_PATH = str(REPO_ROOT / "models.html")
SITEMAP_OUTPUT_PATH = str(REPO_ROOT / "sitemap.xml")
GENERATED_COMMENT = "<!-- GENERATED BY build-html.py — DO NOT EDIT -->"


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_models():
    """Scan models/*/model.json and return list sorted by sort_order (excluding sort_order 0)."""
    models = []
    pattern = os.path.join(MODELS_DATA_DIR, "*", "model.json")
    for json_path in glob.glob(pattern):
        dir_name = os.path.basename(os.path.dirname(json_path))
        if dir_name.startswith("_"):  # Skip _template
            continue
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if data.get("sort_order", 0) <= 0:
            # Clean up index.html if it was previously generated for a 0 sort_order model
            idx_file = os.path.join(os.path.dirname(json_path), "index.html")
            if os.path.exists(idx_file):
                os.remove(idx_file)
            continue
        models.append(data)
    models.sort(key=lambda m: m.get("sort_order", 0), reverse=True)
    return models


# ---------------------------------------------------------------------------
# HTML rendering helpers
# ---------------------------------------------------------------------------

def render_sections(sections):
    """Convert sections list to HTML string."""
    parts = []
    for section in sections:
        heading = section.get("heading", "")
        if heading:
            parts.append(f"                    <h3>{heading}</h3>")

        if section["type"] == "text":
            content = section.get("content", "")
            for para in content.split("\n"):
                para = para.strip()
                if para:
                    parts.append(f"                    <p>{para}</p>")

        elif section["type"] == "list":
            parts.append("                    <ul>")
            for item in section.get("items", []):
                parts.append(f"                        <li>{item}</li>")
            parts.append("                    </ul>")

    return "\n".join(parts)


def render_media_nav(media):
    """Render prev/next nav buttons if multiple media items."""
    if len(media) <= 1:
        return ""
    return """                    <div class="nav-btn-container">
                        <button class="nav-btn prev">&lt;</button>
                        <button class="nav-btn next">&gt;</button>
                    </div>"""


def escape_for_html_attr(text):
    """Escape text for use in HTML attributes."""
    return text.replace("&", "&amp;").replace('"', "&quot;").replace("<", "&lt;").replace(">", "&gt;")


# ---------------------------------------------------------------------------
# Template: Individual model page
# ---------------------------------------------------------------------------

MODEL_PAGE_TEMPLATE = r"""%%GENERATED_COMMENT%%
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>%%TITLE%% | juke^32</title>
    <meta name="description" content="%%META_DESCRIPTION%%">
    <meta property="og:title" content="%%TITLE%% | juke^32">
    <meta property="og:description" content="%%META_DESCRIPTION%%">
    <meta property="og:image" content="%%SITE_URL%%/%%THUMBNAIL%%">
    <meta property="og:url" content="%%SITE_URL%%/models/%%SLUG%%/">
    <meta property="og:type" content="website">
    <link rel="canonical" href="%%SITE_URL%%/models/%%SLUG%%/">
    <link rel="preload" href="/assets/fonts/Monocraft.otf" as="font" type="font/otf" crossorigin>
    <link rel="preload" href="/assets/fonts/minecraft-sga.ttf" as="font" type="font/ttf" crossorigin>
    <link rel="stylesheet" href="../../models.css">
    <script src="../../particles.js"></script>
    <script src="../../script.js" defer></script>
    <link rel="icon" href="/assets/images/favicon.ico" type="image/x-icon">
    <link rel="icon" sizes="32x32" href="/assets/images/favicon-32x32.png" type="image/png">
    <link rel="icon" sizes="64x64" href="/assets/images/favicon-64x64.png" type="image/png">
</head>
<body>
    <div id="particles-js"></div>
    <a href="#" id="toggle-font" class="corner-link top-left">sga</a>
    <a href="../../models.html" class="corner-link top-right">back</a>
    <a href="https://www.youtube.com/@jukebox.32" class="corner-link bottom-left">youtube</a>
    <a href="https://discord.gg/6bJySHXChG" class="corner-link bottom-right">discord</a>

    <div class="main-container">
        <h1><a href="../../models.html" style="color: inherit; text-decoration: none;">%%TITLE%%</a></h1>
        <div class="scroll-container">
            <div class="model-page-content">
                <div class="media-container">
                    <div class="media-display"></div>
%%MEDIA_NAV%%
                </div>
                <div class="popup-text">
%%SECTIONS_HTML%%
                </div>
            </div>
        </div>
    </div>

    <div id="preload-container" style="display: none;"></div>
    <audio id="bg-audio" src="/assets/sound/PrettyDecent - Juke.mp3" loop></audio>
    <div id="current-track"><span id="track-name"></span></div>

    <script>
        // Media gallery for this model page
        const mediaItems = %%MEDIA_JSON%%;
        let currentIndex = 0;
        const mediaDisplay = document.querySelector('.media-display');
        const preloadContainer = document.getElementById('preload-container');

        function getSrc(src) {
            return src;
        }

        function showMedia(index) {
            // Pause any currently playing video before switching
            const currentVideo = mediaDisplay.querySelector('video');
            if (currentVideo) { currentVideo.pause(); }

            const item = mediaItems[index];
            if (item.type === 'image') {
                mediaDisplay.innerHTML = '<img src="' + getSrc(item.src) + '" class="popup-image" alt="View">';
            } else if (item.type === 'video') {
                const ext = item.src.split('.').pop();
                mediaDisplay.innerHTML =
                    '<video class="popup-video" controls preload="metadata" playsinline>' +
                    '<source src="' + getSrc(item.src) + '" type="video/' + ext + '">' +
                    'Your browser does not support the video tag.' +
                    '</video>';
            }
        }

        function preloadImages() {
            if (!preloadContainer) return;
            preloadContainer.innerHTML = '';
            mediaItems.forEach(function(item) {
                if (item.type === 'image') {
                    var img = new Image();
                    img.src = getSrc(item.src);
                    preloadContainer.appendChild(img);
                    if ('decode' in img) img.decode().catch(function() {});
                }
            });
        }

        showMedia(0);
        preloadImages();

        var prevBtn = document.querySelector('.prev');
        var nextBtn = document.querySelector('.next');

        if (prevBtn) {
            prevBtn.addEventListener('click', function(e) {
                e.stopPropagation();
                currentIndex = (currentIndex - 1 + mediaItems.length) % mediaItems.length;
                showMedia(currentIndex);
            });
        }
        if (nextBtn) {
            nextBtn.addEventListener('click', function(e) {
                e.stopPropagation();
                currentIndex = (currentIndex + 1) % mediaItems.length;
                showMedia(currentIndex);
            });
        }

        // Pause video when leaving the page
        window.addEventListener('pagehide', function() {
            var video = document.querySelector('video');
            if (video) { video.pause(); }
        });
    </script>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Template: Models grid page
# ---------------------------------------------------------------------------

MODELS_GRID_TEMPLATE = r"""%%GENERATED_COMMENT%%
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>juke^32 models</title>
    <meta name="description" content="All juke^32 models — Minecraft-inspired jukeboxes and speakers.">
    <meta property="og:title" content="juke^32 models">
    <meta property="og:description" content="All juke^32 models — Minecraft-inspired jukeboxes and speakers.">
    <meta property="og:url" content="%%SITE_URL%%/models.html">
    <meta property="og:type" content="website">
    <link rel="canonical" href="%%SITE_URL%%/models.html">
    <link rel="preload" href="assets/fonts/Monocraft.otf" as="font" type="font/otf" crossorigin>
    <link rel="preload" href="assets/fonts/minecraft-sga.ttf" as="font" type="font/ttf" crossorigin>
    <link rel="stylesheet" href="models.css">
    <script src="particles.js"></script>
    <script src="script.js" defer></script>
    <link rel="icon" href="assets/images/favicon.ico" type="image/x-icon">
    <link rel="icon" sizes="32x32" href="assets/images/favicon-32x32.png" type="image/png">
    <link rel="icon" sizes="64x64" href="assets/images/favicon-64x64.png" type="image/png">
</head>
<body>
    <div id="particles-js"></div>
    <a href="#" id="toggle-font" class="corner-link top-left">sga</a>
    <a href="index.html" class="corner-link top-right">home</a>
    <a href="https://www.youtube.com/@jukebox.32" class="corner-link bottom-left">youtube</a>
    <a href="https://discord.gg/6bJySHXChG" class="corner-link bottom-right">discord</a>

    <div class="main-container">
        <h1><a href="index.html" style="color: inherit; text-decoration: none;">models</a></h1>
        <div class="scroll-container">
            <div class="model-grid">
%%MODEL_BOXES%%
            </div>
        </div>
    </div>
    <div id="preload-container" style="display: none;"></div>
    <audio id="bg-audio" src="assets/sound/PrettyDecent - Juke.mp3" loop></audio>
    <div id="current-track"><span id="track-name"></span></div>
</body>
</html>
"""


MODEL_BOX_TEMPLATE = """                <a href="models/%%SLUG%%/index.html" class="model-box" data-text="%%TAGLINE_ATTR%%">
                    <div class="image-container">
                        <img src="models/%%SLUG%%/%%THUMBNAIL%%" alt="%%TITLE_ATTR%%">
                    </div>
                    <div class="hover-text">
                        %%HOVER_TEXT%%
                    </div>
                </a>
"""


# ---------------------------------------------------------------------------
# Sitemap template
# ---------------------------------------------------------------------------

SITEMAP_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
%%URLS%%</urlset>
"""

SITEMAP_URL = """   <url>
      <loc>%%LOC%%</loc>
   </url>
"""


# ---------------------------------------------------------------------------
# Generation functions
# ---------------------------------------------------------------------------

def generate_model_page(model):
    """Generate HTML for an individual model page."""
    html = MODEL_PAGE_TEMPLATE
    html = html.replace("%%GENERATED_COMMENT%%", GENERATED_COMMENT)
    html = html.replace("%%SITE_URL%%", SITE_URL)
    html = html.replace("%%TITLE%%", model["title"])
    html = html.replace("%%SLUG%%", model["slug"])
    html = html.replace("%%META_DESCRIPTION%%", escape_for_html_attr(model.get("meta_description", model["tagline"])))
    html = html.replace("%%THUMBNAIL%%", model["thumbnail"])
    html = html.replace("%%SECTIONS_HTML%%", render_sections(model.get("sections", [])))
    html = html.replace("%%MEDIA_NAV%%", render_media_nav(model.get("media", [])))
    html = html.replace("%%MEDIA_JSON%%", json.dumps(model.get("media", []), indent=8))
    return html


def generate_grid_page(models):
    """Generate the models grid HTML page."""
    boxes = []
    for model in models:
        box = MODEL_BOX_TEMPLATE
        box = box.replace("%%SLUG%%", model["slug"])
        box = box.replace("%%TAGLINE_ATTR%%", escape_for_html_attr(model["tagline"]))
        box = box.replace("%%THUMBNAIL%%", model["thumbnail"])
        box = box.replace("%%TITLE_ATTR%%", escape_for_html_attr(model["title"]))
        box = box.replace("%%HOVER_TEXT%%", model["hover_text"])
        boxes.append(box)

    html = MODELS_GRID_TEMPLATE
    html = html.replace("%%GENERATED_COMMENT%%", GENERATED_COMMENT)
    html = html.replace("%%SITE_URL%%", SITE_URL)
    html = html.replace("%%MODEL_BOXES%%", "\n".join(boxes))
    return html


def generate_sitemap(models):
    """Generate sitemap.xml with all pages."""
    urls = []
    # Static pages
    urls.append(SITEMAP_URL.replace("%%LOC%%", SITE_URL + "/"))
    urls.append(SITEMAP_URL.replace("%%LOC%%", SITE_URL + "/models.html"))
    # Model pages
    for model in models:
        loc = f"{SITE_URL}/models/{model['slug']}/"
        urls.append(SITEMAP_URL.replace("%%LOC%%", loc))
    return SITEMAP_TEMPLATE.replace("%%URLS%%", "".join(urls))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("build-html.py — generating model pages, grid, and sitemap\n")

    # Load model data
    models = load_models()
    if not models:
        print("  WARNING: No model.json files found in models/*/")
        print("  Expected: models/{model-name}/model.json")
        return

    print(f"  Found {len(models)} models:")
    for m in models:
        print(f"    [{m.get('sort_order', '?')}] {m['slug']}: {m['title']}")

    # Generate individual model pages
    print(f"\n  Generating model pages in {MODELS_OUTPUT_DIR}/...")
    for model in models:
        out_dir = os.path.join(MODELS_OUTPUT_DIR, model["slug"])
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, "index.html")
        html = generate_model_page(model)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"    ✓ {out_path}")

    # Generate grid page
    print("\n  Generating models.html...")
    grid_html = generate_grid_page(models)
    with open(GRID_OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(grid_html)
    print(f"    ✓ {GRID_OUTPUT_PATH}")

    # Generate sitemap
    print("\n  Generating sitemap.xml...")
    sitemap = generate_sitemap(models)
    with open(SITEMAP_OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(sitemap)
    print(f"    ✓ {SITEMAP_OUTPUT_PATH}")

    print(f"\n  Done! Generated {len(models)} model pages + grid + sitemap.")


if __name__ == "__main__":
    main()
